# Generated by Django 2.2.5 on 2019-09-10 13:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('weupdates', '0004_auto_20190906_1005'),
    ]

    operations = [
        migrations.AlterField(
            model_name='action',
            name='pub_date',
            field=models.IntegerField(verbose_name='week published'),
        ),
    ]
